# -*- coding: utf-8 -*-
"""Лабораторная-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2u9ohyoYjBeZe6gYdNq8qjlpgeZoRQi
"""

n = int(input())
if n == 1:
    print("январь")
elif n == 2:
    print("февраль")
elif n == 3:
    print("март")
elif n == 4:
    print("апрель")
elif n == 5:
    print("май")
elif n == 6:
    print("июнь")
elif n == 7:
    print("июль")
elif n == 8:
    print("август")
elif n == 9:
    print("сентябрь")
elif n == 10:
    print("октябрь")
elif n == 11:
    print("ноябрь")
else:
    print("декабрь")

n = int(input())
if n % 2 == 0:
    print("четное")
else:
    print("нечетное")

N = int(input())
if N > 40:
    print("stonks")
else:
    print("not stonks")

n = int(input())
def is_year_leap(n):
    if n % 4 == 0:
        return True
    else:
        return False
print(is_year_leap(n))

n = int(input())
def is_prime(n):
    if n < 1:
        return False
    for i in range(2, n + 1):
        if i != n and n % i == 0:
            return False
    return True
print(is_prime(n))

const1 = (-138 / 2) ** 1.3
const2 = (-69 / (28 ** 5.1)) * 4

a = float(input())
b = float(input())

if a / b == 3.6 or const1.real <= b <= const2.real:
    a, b = b, a

print(a, b)

numbs = []
uniq = []

chet = 0
neg = 0
in_range = 0

for i in range(5):
  numb = int(input())
  numbs.append(numb)

for numb in numbs:
  if not numb in uniq:
    uniq.append(numb)

  if numb % 2 == 0:
    chet += 1
  
  if numb < 0:
    neg += 1

  if numb >= -256 and numb <= 1024:
    in_range += 1
  
if len(numbs) == len(uniq):
  print("все числа уникальны")
else:
  print("не все числа уникальны")

print("четных чисел", chet)
print("отрицательных чисел", neg)
print("количество чисел в промежутке", in_range)

a = float(input())
b = float(input())
c = float(input())

if c != -3:
  ner = ((a ** 2 + b ** 3) / (c + 3)) / 4

  if ner % 2 == 0:
    print("число четное")
  else:
    print("число нечетное")
  
else:
  print("решений нет")