# -*- coding: utf-8 -*-
"""лабораторная №1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_geVUKenYkBbK0QCo6Lt2CtwBnAKY-8W
"""

a = 5
b = int(input())
print(a * b)

a = int(input())
b = int(input())
print((a + b) ** 2)

a = 15
b = 10
c = int(input())
print((a + b) / c)

a = int(input())
b = int(input())
c = a ** 2 + 2 * a * b + b ** 2
print(c)

a = int(input())
b = int(input())
c = int(input())
s = 0.5 * a * c
p = a + b + c
print(s, p)

a = float(input())
b = float(input())
c = int(input())
d = int(input())
s = a // b
p = c * d
f = c % d
print(s, p, f)

n = int(input())
a = n // (24 * 60 * 60)
b = n // (60 * 60)
c = n // 60
print(a, b, c)

n = input()
a = n + n * 2 + n * 3
print(a)